<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_RegressionTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1286ccc6-2057-418d-87af-23d00cc6cd0e</testSuiteGuid>
   <testCaseLink>
      <guid>12b1ed24-3d2b-4bed-87e1-7c72470cdce7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main.Test.Cases/TS_RegressionTest122721</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14d98e7b-4ac8-4e28-8ce7-394001d188f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a97344e7-5f9c-4936-92a2-d85e5463f3c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4bf2157-13c0-4c5f-875c-fa60a7e7a2fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main.Test.Cases/TS_RegressionTestCollection122721</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ae001a50-807e-4ee4-9cc4-484354d5aaed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Folder.1c/Folder.2/Folder.3/Folder.4/Folder.5/Folder.6/TS_RegressionTest010522</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f87a7d1-3991-4e16-8828-ce0745a71777</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c771e12-ae33-40ee-9758-ff728611256b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9220f3cb-60c3-403f-a600-29760ae7efd3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Folder.1b/Folder.2/Folder.3/Folder.4/Folder.5/Folder.6/Folder.7/TS_RegressionTest010522</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc04b6ce-da9a-476a-86c9-3015833f8171</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5ae845f-9b46-4b7b-9af9-7e8d570a43d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1bacc591-d39c-4747-a272-799cc5d2d133</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Folder.1a/Folder.2/Folder.3/Folder.4/Folder.5/Folder.6/Folder.7/Folder.8/TS_RegressionTest010522</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>231e26ae-48ff-47eb-b7af-cc0fa3b256a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b33e73f8-97c5-4907-95e5-c3c4f764048b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>57a2b91f-2eeb-474b-9146-861dbe9b7a07</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Folder.1/Folder.2/Folder.3/Folder.4/Folder.5/Folder.6/Folder.7/Folder.8/Folder.9/TS_RegressionTest010522</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13c5d1e9-a77b-4fd3-aa36-b0770d571405</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9830aa29-d135-4717-9f19-5cf20b6aa436</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
